// Auto generated by build.sh at Fri Oct 25 19:58:42 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("9.0.0.1658")]
[assembly: AssemblyFileVersion("9.0.0.1658")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.Client.VisualStudio/wiki")]

[assembly: AssemblyProduct("VersionOne.VisualStudio.DataLayer")]
[assembly: AssemblyTitle("VersionOne.VisualStudio.DataLayer")]
[assembly: AssemblyDescription("VersionOne Client for Visual Studio VersionOne.VisualStudio.DataLayer Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
